import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingDockDemo } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#6A7FDB] flex flex-col min-h-screen ${inter.className}`}>
        <main className="flex-grow overflow-auto pb-16">
          {children}
        </main>
        <div className="fixed bottom-0 left-0 right-0">
          <FloatingDockDemo />
        </div>
      </body>
    </html>
  );
}
